/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditEntry {
  'id' : bigint,
  'action' : string,
  'target' : [] | [Principal],
  'timestamp' : Time,
  'caller' : Principal,
  'outcome' : AuditOutcome,
}
export type AuditOutcome = { 'ok' : null } |
  { 'err' : string };
export interface CertificatePayload {
  'signature' : Uint8Array,
  'auditEntryCount' : bigint,
  'publicKey' : Uint8Array,
  'certificateId' : string,
  'lastAuditTimestamp' : bigint,
  'masterController' : string,
  'issuedAt' : bigint,
  'unauthorizedAttempts' : bigint,
  'canisterId' : string,
  'validUntil' : bigint,
}
export interface Client {
  'id' : bigint,
  'status' : ClientStatus,
  'clientType' : ClientType,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'primaryEmail' : [] | [string],
  'notes' : string,
  'lastModifiedAt' : Time,
  'lastModifiedBy' : Principal,
  'primaryPhone' : [] | [string],
  'identifier' : [] | [string],
}
export interface ClientFilter {
  'createdBefore' : [] | [Time],
  'nameContains' : [] | [string],
  'clientType' : [] | [ClientType],
  'createdAfter' : [] | [Time],
  'statusFilter' : [] | [ClientStatus],
  'identifierContains' : [] | [string],
}
export type ClientStatus = { 'Inactive' : null } |
  { 'Active' : null };
export interface ClientStatusCounts { 'active' : bigint, 'inactive' : bigint }
export type ClientType = { 'Company' : null } |
  { 'Individual' : null } |
  { 'Other' : null };
export interface Document {
  'id' : bigint,
  'status' : DocumentStatus,
  'createdAt' : Time,
  'createdBy' : Principal,
  'matterId' : bigint,
  'currentVersionId' : bigint,
}
export interface DocumentFilter {
  'contentType' : [] | [string],
  'filenameContains' : [] | [string],
  'matterId' : [] | [bigint],
  'uploadedAfter' : [] | [Time],
  'statusFilter' : [] | [DocumentStatus],
  'uploadedBy' : [] | [Principal],
  'uploadedBefore' : [] | [Time],
}
export interface DocumentSearchResult {
  'currentVersion' : DocumentVersion,
  'document' : Document,
}
export type DocumentStatus = { 'Active' : null } |
  { 'Deleted' : null };
export interface DocumentStatusCounts { 'deleted' : bigint, 'active' : bigint }
export interface DocumentVersion {
  'versionId' : bigint,
  'sha256' : Uint8Array,
  'contentType' : string,
  'blob' : Uint8Array,
  'filename' : string,
  'documentId' : bigint,
  'sizeBytes' : bigint,
  'uploadNotes' : string,
  'versionNumber' : bigint,
  'uploadedAt' : Time,
  'uploadedBy' : Principal,
}
export interface ExportManifest {
  'libraryItems' : Array<{ 'itemId' : bigint, 'versionIds' : Array<bigint> }>,
  'totalVersions' : bigint,
  'totalFolders' : bigint,
  'documents' : Array<{ 'versionIds' : Array<bigint>, 'documentId' : bigint }>,
  'matterIds' : Array<bigint>,
  'totalLibraryItems' : bigint,
  'totalMatters' : bigint,
  'generatedAt' : Time,
  'generatedBy' : Principal,
  'userPrincipals' : Array<Principal>,
  'folders' : Array<Folder>,
  'totalLibraryVersions' : bigint,
  'storageUsedBytes' : bigint,
  'masterController' : Principal,
  'totalClients' : bigint,
  'storageBudgetBytes' : bigint,
  'clientIds' : Array<bigint>,
  'totalAuditEntries' : bigint,
  'operationsPrincipal' : [] | [Principal],
  'totalDocuments' : bigint,
}
export type FileAccessKind = { 'View' : null } |
  { 'Download' : null };
export interface Folder {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'parentId' : [] | [bigint],
}
export interface FolderListing {
  'folders' : Array<Folder>,
  'items' : Array<LibraryItemSearchResult>,
}
export type FolderScope = { 'Any' : null } |
  { 'Folder' : bigint } |
  { 'Root' : null } |
  { 'Subtree' : bigint };
export interface LibraryFilter {
  'folderScope' : FolderScope,
  'currentFilenameContains' : [] | [string],
  'contentType' : [] | [string],
  'nameContains' : [] | [string],
  'uploadedAfter' : [] | [Time],
  'tagsContainsAny' : [] | [Array<string>],
  'statusFilter' : [] | [LibraryItemStatus],
  'uploadedBy' : [] | [Principal],
  'uploadedBefore' : [] | [Time],
}
export interface LibraryItem {
  'id' : bigint,
  'status' : LibraryItemStatus,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'tags' : Array<string>,
  'description' : string,
  'folderId' : [] | [bigint],
  'currentVersionId' : bigint,
}
export interface LibraryItemSearchResult {
  'item' : LibraryItem,
  'currentVersion' : LibraryVersion,
}
export type LibraryItemStatus = { 'Active' : null } |
  { 'Archived' : null } |
  { 'Deleted' : null };
export interface LibraryVersion {
  'itemId' : bigint,
  'versionId' : bigint,
  'sha256' : Uint8Array,
  'contentType' : string,
  'blob' : Uint8Array,
  'filename' : string,
  'sizeBytes' : bigint,
  'uploadNotes' : string,
  'versionNumber' : bigint,
  'uploadedAt' : Time,
  'uploadedBy' : Principal,
}
export interface Matter {
  'id' : bigint,
  'status' : MatterStatus,
  'title' : string,
  'clientId' : bigint,
  'createdAt' : Time,
  'createdBy' : Principal,
  'description' : string,
  'closedAt' : [] | [Time],
  'lastModifiedAt' : Time,
  'lastModifiedBy' : Principal,
  'matterType' : string,
  'assignedPartner' : [] | [Principal],
  'openedAt' : Time,
}
export interface MatterFilter {
  'openedBefore' : [] | [Time],
  'clientId' : [] | [bigint],
  'closedAfter' : [] | [Time],
  'titleContains' : [] | [string],
  'closedBefore' : [] | [Time],
  'openedAfter' : [] | [Time],
  'statusFilter' : [] | [MatterStatus],
  'matterTypeContains' : [] | [string],
  'assignedPartner' : [] | [Principal],
}
export type MatterStatus = { 'OnHold' : null } |
  { 'Open' : null } |
  { 'Closed' : null } |
  { 'Archived' : null };
export interface MatterStatusCounts {
  'closed' : bigint,
  'open' : bigint,
  'onHold' : bigint,
  'archived' : bigint,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_2 = { 'ok' : Array<AuditEntry> } |
  { 'err' : string };
export type Result_3 = {
    'ok' : {
      'itemId' : bigint,
      'versionId' : bigint,
      'sha256' : Uint8Array,
      'contentType' : string,
      'filename' : string,
      'chunkCount' : bigint,
      'sizeBytes' : bigint,
    }
  } |
  { 'err' : string };
export type Result_4 = {
    'ok' : {
      'sha256' : Uint8Array,
      'contentType' : string,
      'filename' : string,
      'chunkCount' : bigint,
      'documentId' : bigint,
      'sizeBytes' : bigint,
    }
  } |
  { 'err' : string };
export type Result_5 = { 'ok' : { 'skipped' : bigint, 'migrated' : bigint } } |
  { 'err' : string };
export type Result_6 = {
    'ok' : {
      'versionId' : bigint,
      'sha256' : Uint8Array,
      'documentId' : bigint,
    }
  } |
  { 'err' : string };
export type Result_7 = {
    'ok' : { 'itemId' : bigint, 'versionId' : bigint, 'sha256' : Uint8Array }
  } |
  { 'err' : string };
export type Result_8 = { 'ok' : ExportManifest } |
  { 'err' : string };
export type Result_9 = { 'ok' : CertificatePayload } |
  { 'err' : string };
export type Role = { 'Staff' : null } |
  { 'Associate' : null } |
  { 'Partner' : null };
export interface ThePractice {
  'abandonLibraryUpload' : ActorMethod<[bigint], Result>,
  'abandonUpload' : ActorMethod<[bigint], Result>,
  'addLibraryItemTag' : ActorMethod<[bigint, string], Result>,
  'addUser' : ActorMethod<[Principal, Role], Result>,
  'appendChunk' : ActorMethod<[bigint, bigint, Uint8Array], Result>,
  'appendLibraryChunk' : ActorMethod<[bigint, bigint, Uint8Array], Result>,
  'archiveLibraryItem' : ActorMethod<[bigint], Result>,
  'archiveMatter' : ActorMethod<[bigint], Result>,
  'assignPartnerToMatter' : ActorMethod<[bigint, [] | [Principal]], Result>,
  'cancelTopUpRequest' : ActorMethod<[bigint], Result>,
  'clientsByStatus' : ActorMethod<[], ClientStatusCounts>,
  'closeMatter' : ActorMethod<[bigint], Result>,
  'createClient' : ActorMethod<
    [string, ClientType, [] | [string], [] | [string], [] | [string], string],
    Result_1
  >,
  'createExportManifest' : ActorMethod<[], Result_8>,
  'createFolder' : ActorMethod<[string, [] | [bigint]], Result_1>,
  'createMatter' : ActorMethod<
    [string, string, bigint, [] | [Principal], string],
    Result_1
  >,
  'createTopUpRequest' : ActorMethod<[bigint, string], Result_1>,
  'deactivateClient' : ActorMethod<[bigint], Result>,
  'deleteDocument' : ActorMethod<[bigint], Result>,
  'deleteFolder' : ActorMethod<[bigint], Result>,
  'deleteLibraryItem' : ActorMethod<[bigint], Result>,
  'documentsByStatus' : ActorMethod<[], DocumentStatusCounts>,
  'finalizeLibraryUpload' : ActorMethod<[bigint], Result_7>,
  'finalizeUpload' : ActorMethod<[bigint], Result_6>,
  'fulfillTopUpRequest' : ActorMethod<[bigint], Result>,
  'generateComplianceCertificate' : ActorMethod<[], Result_9>,
  'getChunk' : ActorMethod<[bigint, bigint], [] | [Uint8Array]>,
  'getClient' : ActorMethod<[bigint], [] | [Client]>,
  'getClientCount' : ActorMethod<[], bigint>,
  'getCycleBalance' : ActorMethod<[], bigint>,
  'getDocument' : ActorMethod<[bigint], [] | [Document]>,
  'getDocumentCount' : ActorMethod<[], bigint>,
  'getDocumentVersion' : ActorMethod<[bigint], [] | [DocumentVersion]>,
  'getFolder' : ActorMethod<[bigint], [] | [Folder]>,
  'getFolderCount' : ActorMethod<[], bigint>,
  'getFolderDepth' : ActorMethod<[bigint], [] | [bigint]>,
  'getLibraryChunk' : ActorMethod<[bigint, bigint], [] | [Uint8Array]>,
  'getLibraryItem' : ActorMethod<[bigint], [] | [LibraryItem]>,
  'getLibraryItemCount' : ActorMethod<[], bigint>,
  'getLibraryVersion' : ActorMethod<[bigint], [] | [LibraryVersion]>,
  'getMasterController' : ActorMethod<[], Principal>,
  'getMatter' : ActorMethod<[bigint], [] | [Matter]>,
  'getMatterCount' : ActorMethod<[], bigint>,
  'getMyRole' : ActorMethod<[], [] | [Role]>,
  'getOperationsPrincipal' : ActorMethod<[], [] | [Principal]>,
  'getStorageBudget' : ActorMethod<[], bigint>,
  'getStorageUsed' : ActorMethod<[], bigint>,
  'getTopUpRequest' : ActorMethod<[bigint], [] | [TopUpRequestRecord]>,
  'getUserCount' : ActorMethod<[], bigint>,
  'grantOperations' : ActorMethod<[Principal], Result>,
  'listAllFolders' : ActorMethod<[], Array<Folder>>,
  'listClients' : ActorMethod<[bigint, bigint, boolean], Array<Client>>,
  'listDocumentsByMatter' : ActorMethod<
    [bigint, bigint, bigint, boolean],
    Array<Document>
  >,
  'listFolderContents' : ActorMethod<[FolderScope], FolderListing>,
  'listLibraryItems' : ActorMethod<
    [LibraryFilter, bigint, bigint],
    Array<LibraryItemSearchResult>
  >,
  'listLibraryVersions' : ActorMethod<[bigint], Array<LibraryVersion>>,
  'listMatters' : ActorMethod<
    [bigint, bigint, [] | [MatterStatus]],
    Array<Matter>
  >,
  'listMattersByClient' : ActorMethod<
    [bigint, bigint, bigint, [] | [MatterStatus]],
    Array<Matter>
  >,
  'listTopUpRequests' : ActorMethod<
    [[] | [TopUpRequestStatus]],
    Array<TopUpRequestRecord>
  >,
  'listUsers' : ActorMethod<[], Array<[Principal, UserRecord]>>,
  'listVersions' : ActorMethod<[bigint], Array<DocumentVersion>>,
  'mattersByStatus' : ActorMethod<[], MatterStatusCounts>,
  'migrateDocumentVersions' : ActorMethod<[], Result_5>,
  'migrateLibraryVersions' : ActorMethod<[], Result_5>,
  'moveFolder' : ActorMethod<[bigint, [] | [bigint]], Result>,
  'moveLibraryItem' : ActorMethod<[bigint, [] | [bigint]], Result>,
  'prepareDocumentDownload' : ActorMethod<[bigint, FileAccessKind], Result_4>,
  'prepareLibraryDownload' : ActorMethod<[bigint, FileAccessKind], Result_3>,
  'putMatterOnHold' : ActorMethod<[bigint], Result>,
  'reactivateClient' : ActorMethod<[bigint], Result>,
  'readAuditEntries' : ActorMethod<[bigint, bigint], Result_2>,
  'removeLibraryItemTag' : ActorMethod<[bigint, string], Result>,
  'removeUser' : ActorMethod<[Principal], Result>,
  'renameFolder' : ActorMethod<[bigint, string], Result>,
  'renameLibraryItem' : ActorMethod<[bigint, string], Result>,
  'reopenMatter' : ActorMethod<[bigint], Result>,
  'resumeMatter' : ActorMethod<[bigint], Result>,
  'revokeOperations' : ActorMethod<[], Result>,
  'searchClients' : ActorMethod<[ClientFilter, bigint, bigint], Array<Client>>,
  'searchDocuments' : ActorMethod<
    [DocumentFilter, bigint, bigint],
    Array<DocumentSearchResult>
  >,
  'searchLibrary' : ActorMethod<
    [LibraryFilter, bigint, bigint],
    Array<LibraryItemSearchResult>
  >,
  'searchMatters' : ActorMethod<[MatterFilter, bigint, bigint], Array<Matter>>,
  'setLibraryItemTags' : ActorMethod<[bigint, Array<string>], Result>,
  'setStorageBudget' : ActorMethod<[bigint], Result>,
  'setUserRole' : ActorMethod<[Principal, Role], Result>,
  'startLibraryUpload' : ActorMethod<
    [
      string,
      [] | [bigint],
      Array<string>,
      string,
      string,
      string,
      bigint,
      string,
      [] | [bigint],
    ],
    Result_1
  >,
  'startUpload' : ActorMethod<
    [bigint, string, string, bigint, string, [] | [bigint]],
    Result_1
  >,
  'suspendUser' : ActorMethod<[Principal], Result>,
  'transferMasterController' : ActorMethod<[Principal], Result>,
  'unarchiveLibraryItem' : ActorMethod<[bigint], Result>,
  'unsuspendUser' : ActorMethod<[Principal], Result>,
  'updateClient' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [ClientType],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    Result
  >,
  'updateLibraryItemDescription' : ActorMethod<[bigint, string], Result>,
  'updateMatter' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [[] | [Principal]],
      [] | [string],
    ],
    Result
  >,
  'whoAmI' : ActorMethod<[], Principal>,
}
export type Time = bigint;
export interface TopUpRequestRecord {
  'id' : bigint,
  'status' : TopUpRequestStatus,
  'note' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'requestedTrillionCycles' : bigint,
  'cancelledAt' : [] | [Time],
  'cancelledBy' : [] | [Principal],
  'fulfilledAt' : [] | [Time],
  'fulfilledBy' : [] | [Principal],
}
export type TopUpRequestStatus = { 'Cancelled' : null } |
  { 'Fulfilled' : null } |
  { 'Pending' : null };
export interface UserRecord {
  'role' : Role,
  'addedAt' : Time,
  'addedBy' : Principal,
  'suspended' : boolean,
}
export interface _SERVICE extends ThePractice {}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];