/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Role = IDL.Variant({
    'Staff' : IDL.Null,
    'Associate' : IDL.Null,
    'Partner' : IDL.Null,
  });
  const ClientStatusCounts = IDL.Record({
    'active' : IDL.Nat,
    'inactive' : IDL.Nat,
  });
  const ClientType = IDL.Variant({
    'Company' : IDL.Null,
    'Individual' : IDL.Null,
    'Other' : IDL.Null,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const Time = IDL.Int;
  const Folder = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'parentId' : IDL.Opt(IDL.Nat),
  });
  const ExportManifest = IDL.Record({
    'libraryItems' : IDL.Vec(
      IDL.Record({ 'itemId' : IDL.Nat, 'versionIds' : IDL.Vec(IDL.Nat) })
    ),
    'totalVersions' : IDL.Nat,
    'totalFolders' : IDL.Nat,
    'documents' : IDL.Vec(
      IDL.Record({ 'versionIds' : IDL.Vec(IDL.Nat), 'documentId' : IDL.Nat })
    ),
    'matterIds' : IDL.Vec(IDL.Nat),
    'totalLibraryItems' : IDL.Nat,
    'totalMatters' : IDL.Nat,
    'generatedAt' : Time,
    'generatedBy' : IDL.Principal,
    'userPrincipals' : IDL.Vec(IDL.Principal),
    'folders' : IDL.Vec(Folder),
    'totalLibraryVersions' : IDL.Nat,
    'storageUsedBytes' : IDL.Nat,
    'masterController' : IDL.Principal,
    'totalClients' : IDL.Nat,
    'storageBudgetBytes' : IDL.Nat,
    'clientIds' : IDL.Vec(IDL.Nat),
    'totalAuditEntries' : IDL.Nat,
    'operationsPrincipal' : IDL.Opt(IDL.Principal),
    'totalDocuments' : IDL.Nat,
  });
  const Result_8 = IDL.Variant({ 'ok' : ExportManifest, 'err' : IDL.Text });
  const DocumentStatusCounts = IDL.Record({
    'deleted' : IDL.Nat,
    'active' : IDL.Nat,
  });
  const Result_7 = IDL.Variant({
    'ok' : IDL.Record({
      'itemId' : IDL.Nat,
      'versionId' : IDL.Nat,
      'sha256' : IDL.Vec(IDL.Nat8),
    }),
    'err' : IDL.Text,
  });
  const Result_6 = IDL.Variant({
    'ok' : IDL.Record({
      'versionId' : IDL.Nat,
      'sha256' : IDL.Vec(IDL.Nat8),
      'documentId' : IDL.Nat,
    }),
    'err' : IDL.Text,
  });
  const CertificatePayload = IDL.Record({
    'signature' : IDL.Vec(IDL.Nat8),
    'auditEntryCount' : IDL.Nat,
    'publicKey' : IDL.Vec(IDL.Nat8),
    'certificateId' : IDL.Text,
    'lastAuditTimestamp' : IDL.Int,
    'masterController' : IDL.Text,
    'issuedAt' : IDL.Int,
    'unauthorizedAttempts' : IDL.Nat,
    'canisterId' : IDL.Text,
    'validUntil' : IDL.Int,
  });
  const Result_9 = IDL.Variant({ 'ok' : CertificatePayload, 'err' : IDL.Text });
  const ClientStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
  });
  const Client = IDL.Record({
    'id' : IDL.Nat,
    'status' : ClientStatus,
    'clientType' : ClientType,
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'primaryEmail' : IDL.Opt(IDL.Text),
    'notes' : IDL.Text,
    'lastModifiedAt' : Time,
    'lastModifiedBy' : IDL.Principal,
    'primaryPhone' : IDL.Opt(IDL.Text),
    'identifier' : IDL.Opt(IDL.Text),
  });
  const DocumentStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Deleted' : IDL.Null,
  });
  const Document = IDL.Record({
    'id' : IDL.Nat,
    'status' : DocumentStatus,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'matterId' : IDL.Nat,
    'currentVersionId' : IDL.Nat,
  });
  const DocumentVersion = IDL.Record({
    'versionId' : IDL.Nat,
    'sha256' : IDL.Vec(IDL.Nat8),
    'contentType' : IDL.Text,
    'blob' : IDL.Vec(IDL.Nat8),
    'filename' : IDL.Text,
    'documentId' : IDL.Nat,
    'sizeBytes' : IDL.Nat,
    'uploadNotes' : IDL.Text,
    'versionNumber' : IDL.Nat,
    'uploadedAt' : Time,
    'uploadedBy' : IDL.Principal,
  });
  const LibraryItemStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Archived' : IDL.Null,
    'Deleted' : IDL.Null,
  });
  const LibraryItem = IDL.Record({
    'id' : IDL.Nat,
    'status' : LibraryItemStatus,
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'folderId' : IDL.Opt(IDL.Nat),
    'currentVersionId' : IDL.Nat,
  });
  const LibraryVersion = IDL.Record({
    'itemId' : IDL.Nat,
    'versionId' : IDL.Nat,
    'sha256' : IDL.Vec(IDL.Nat8),
    'contentType' : IDL.Text,
    'blob' : IDL.Vec(IDL.Nat8),
    'filename' : IDL.Text,
    'sizeBytes' : IDL.Nat,
    'uploadNotes' : IDL.Text,
    'versionNumber' : IDL.Nat,
    'uploadedAt' : Time,
    'uploadedBy' : IDL.Principal,
  });
  const MatterStatus = IDL.Variant({
    'OnHold' : IDL.Null,
    'Open' : IDL.Null,
    'Closed' : IDL.Null,
    'Archived' : IDL.Null,
  });
  const Matter = IDL.Record({
    'id' : IDL.Nat,
    'status' : MatterStatus,
    'title' : IDL.Text,
    'clientId' : IDL.Nat,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'closedAt' : IDL.Opt(Time),
    'lastModifiedAt' : Time,
    'lastModifiedBy' : IDL.Principal,
    'matterType' : IDL.Text,
    'assignedPartner' : IDL.Opt(IDL.Principal),
    'openedAt' : Time,
  });
  const TopUpRequestStatus = IDL.Variant({
    'Cancelled' : IDL.Null,
    'Fulfilled' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const TopUpRequestRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : TopUpRequestStatus,
    'note' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'requestedTrillionCycles' : IDL.Nat,
    'cancelledAt' : IDL.Opt(Time),
    'cancelledBy' : IDL.Opt(IDL.Principal),
    'fulfilledAt' : IDL.Opt(Time),
    'fulfilledBy' : IDL.Opt(IDL.Principal),
  });
  const FolderScope = IDL.Variant({
    'Any' : IDL.Null,
    'Folder' : IDL.Nat,
    'Root' : IDL.Null,
    'Subtree' : IDL.Nat,
  });
  const LibraryItemSearchResult = IDL.Record({
    'item' : LibraryItem,
    'currentVersion' : LibraryVersion,
  });
  const FolderListing = IDL.Record({
    'folders' : IDL.Vec(Folder),
    'items' : IDL.Vec(LibraryItemSearchResult),
  });
  const LibraryFilter = IDL.Record({
    'folderScope' : FolderScope,
    'currentFilenameContains' : IDL.Opt(IDL.Text),
    'contentType' : IDL.Opt(IDL.Text),
    'nameContains' : IDL.Opt(IDL.Text),
    'uploadedAfter' : IDL.Opt(Time),
    'tagsContainsAny' : IDL.Opt(IDL.Vec(IDL.Text)),
    'statusFilter' : IDL.Opt(LibraryItemStatus),
    'uploadedBy' : IDL.Opt(IDL.Principal),
    'uploadedBefore' : IDL.Opt(Time),
  });
  const UserRecord = IDL.Record({
    'role' : Role,
    'addedAt' : Time,
    'addedBy' : IDL.Principal,
    'suspended' : IDL.Bool,
  });
  const MatterStatusCounts = IDL.Record({
    'closed' : IDL.Nat,
    'open' : IDL.Nat,
    'onHold' : IDL.Nat,
    'archived' : IDL.Nat,
  });
  const Result_5 = IDL.Variant({
    'ok' : IDL.Record({ 'skipped' : IDL.Nat, 'migrated' : IDL.Nat }),
    'err' : IDL.Text,
  });
  const FileAccessKind = IDL.Variant({
    'View' : IDL.Null,
    'Download' : IDL.Null,
  });
  const Result_4 = IDL.Variant({
    'ok' : IDL.Record({
      'sha256' : IDL.Vec(IDL.Nat8),
      'contentType' : IDL.Text,
      'filename' : IDL.Text,
      'chunkCount' : IDL.Nat,
      'documentId' : IDL.Nat,
      'sizeBytes' : IDL.Nat,
    }),
    'err' : IDL.Text,
  });
  const Result_3 = IDL.Variant({
    'ok' : IDL.Record({
      'itemId' : IDL.Nat,
      'versionId' : IDL.Nat,
      'sha256' : IDL.Vec(IDL.Nat8),
      'contentType' : IDL.Text,
      'filename' : IDL.Text,
      'chunkCount' : IDL.Nat,
      'sizeBytes' : IDL.Nat,
    }),
    'err' : IDL.Text,
  });
  const AuditOutcome = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const AuditEntry = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'target' : IDL.Opt(IDL.Principal),
    'timestamp' : Time,
    'caller' : IDL.Principal,
    'outcome' : AuditOutcome,
  });
  const Result_2 = IDL.Variant({
    'ok' : IDL.Vec(AuditEntry),
    'err' : IDL.Text,
  });
  const ClientFilter = IDL.Record({
    'createdBefore' : IDL.Opt(Time),
    'nameContains' : IDL.Opt(IDL.Text),
    'clientType' : IDL.Opt(ClientType),
    'createdAfter' : IDL.Opt(Time),
    'statusFilter' : IDL.Opt(ClientStatus),
    'identifierContains' : IDL.Opt(IDL.Text),
  });
  const DocumentFilter = IDL.Record({
    'contentType' : IDL.Opt(IDL.Text),
    'filenameContains' : IDL.Opt(IDL.Text),
    'matterId' : IDL.Opt(IDL.Nat),
    'uploadedAfter' : IDL.Opt(Time),
    'statusFilter' : IDL.Opt(DocumentStatus),
    'uploadedBy' : IDL.Opt(IDL.Principal),
    'uploadedBefore' : IDL.Opt(Time),
  });
  const DocumentSearchResult = IDL.Record({
    'currentVersion' : DocumentVersion,
    'document' : Document,
  });
  const MatterFilter = IDL.Record({
    'openedBefore' : IDL.Opt(Time),
    'clientId' : IDL.Opt(IDL.Nat),
    'closedAfter' : IDL.Opt(Time),
    'titleContains' : IDL.Opt(IDL.Text),
    'closedBefore' : IDL.Opt(Time),
    'openedAfter' : IDL.Opt(Time),
    'statusFilter' : IDL.Opt(MatterStatus),
    'matterTypeContains' : IDL.Opt(IDL.Text),
    'assignedPartner' : IDL.Opt(IDL.Principal),
  });
  const ThePractice = IDL.Service({
    'abandonLibraryUpload' : IDL.Func([IDL.Nat], [Result], []),
    'abandonUpload' : IDL.Func([IDL.Nat], [Result], []),
    'addLibraryItemTag' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
    'addUser' : IDL.Func([IDL.Principal, Role], [Result], []),
    'appendChunk' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat8)],
        [Result],
        [],
      ),
    'appendLibraryChunk' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat8)],
        [Result],
        [],
      ),
    'archiveLibraryItem' : IDL.Func([IDL.Nat], [Result], []),
    'archiveMatter' : IDL.Func([IDL.Nat], [Result], []),
    'assignPartnerToMatter' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Principal)],
        [Result],
        [],
      ),
    'cancelTopUpRequest' : IDL.Func([IDL.Nat], [Result], []),
    'clientsByStatus' : IDL.Func([], [ClientStatusCounts], ['query']),
    'closeMatter' : IDL.Func([IDL.Nat], [Result], []),
    'createClient' : IDL.Func(
        [
          IDL.Text,
          ClientType,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [Result_1],
        [],
      ),
    'createExportManifest' : IDL.Func([], [Result_8], []),
    'createFolder' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat)], [Result_1], []),
    'createMatter' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Principal), IDL.Text],
        [Result_1],
        [],
      ),
    'createTopUpRequest' : IDL.Func([IDL.Nat, IDL.Text], [Result_1], []),
    'deactivateClient' : IDL.Func([IDL.Nat], [Result], []),
    'deleteDocument' : IDL.Func([IDL.Nat], [Result], []),
    'deleteFolder' : IDL.Func([IDL.Nat], [Result], []),
    'deleteLibraryItem' : IDL.Func([IDL.Nat], [Result], []),
    'documentsByStatus' : IDL.Func([], [DocumentStatusCounts], ['query']),
    'finalizeLibraryUpload' : IDL.Func([IDL.Nat], [Result_7], []),
    'finalizeUpload' : IDL.Func([IDL.Nat], [Result_6], []),
    'fulfillTopUpRequest' : IDL.Func([IDL.Nat], [Result], []),
    'generateComplianceCertificate' : IDL.Func([], [Result_9], []),
    'getChunk' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getClient' : IDL.Func([IDL.Nat], [IDL.Opt(Client)], ['query']),
    'getClientCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getCycleBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getDocument' : IDL.Func([IDL.Nat], [IDL.Opt(Document)], ['query']),
    'getDocumentCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getDocumentVersion' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(DocumentVersion)],
        ['query'],
      ),
    'getFolder' : IDL.Func([IDL.Nat], [IDL.Opt(Folder)], ['query']),
    'getFolderCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getFolderDepth' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
    'getLibraryChunk' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getLibraryItem' : IDL.Func([IDL.Nat], [IDL.Opt(LibraryItem)], ['query']),
    'getLibraryItemCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getLibraryVersion' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(LibraryVersion)],
        ['query'],
      ),
    'getMasterController' : IDL.Func([], [IDL.Principal], ['query']),
    'getMatter' : IDL.Func([IDL.Nat], [IDL.Opt(Matter)], ['query']),
    'getMatterCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
    'getOperationsPrincipal' : IDL.Func(
        [],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getStorageBudget' : IDL.Func([], [IDL.Nat], ['query']),
    'getStorageUsed' : IDL.Func([], [IDL.Nat], ['query']),
    'getTopUpRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(TopUpRequestRecord)],
        ['query'],
      ),
    'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'grantOperations' : IDL.Func([IDL.Principal], [Result], []),
    'listAllFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
    'listClients' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Bool],
        [IDL.Vec(Client)],
        ['query'],
      ),
    'listDocumentsByMatter' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'listFolderContents' : IDL.Func([FolderScope], [FolderListing], ['query']),
    'listLibraryItems' : IDL.Func(
        [LibraryFilter, IDL.Nat, IDL.Nat],
        [IDL.Vec(LibraryItemSearchResult)],
        ['query'],
      ),
    'listLibraryVersions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LibraryVersion)],
        ['query'],
      ),
    'listMatters' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(MatterStatus)],
        [IDL.Vec(Matter)],
        ['query'],
      ),
    'listMattersByClient' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(MatterStatus)],
        [IDL.Vec(Matter)],
        ['query'],
      ),
    'listTopUpRequests' : IDL.Func(
        [IDL.Opt(TopUpRequestStatus)],
        [IDL.Vec(TopUpRequestRecord)],
        ['query'],
      ),
    'listUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserRecord))],
        ['query'],
      ),
    'listVersions' : IDL.Func([IDL.Nat], [IDL.Vec(DocumentVersion)], ['query']),
    'mattersByStatus' : IDL.Func([], [MatterStatusCounts], ['query']),
    'migrateLibraryVersions' : IDL.Func([], [Result_5], []),
    'moveFolder' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Nat)], [Result], []),
    'moveLibraryItem' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Nat)], [Result], []),
    'prepareDocumentDownload' : IDL.Func(
        [IDL.Nat, FileAccessKind],
        [Result_4],
        [],
      ),
    'prepareLibraryDownload' : IDL.Func(
        [IDL.Nat, FileAccessKind],
        [Result_3],
        [],
      ),
    'putMatterOnHold' : IDL.Func([IDL.Nat], [Result], []),
    'reactivateClient' : IDL.Func([IDL.Nat], [Result], []),
    'readAuditEntries' : IDL.Func([IDL.Nat, IDL.Nat], [Result_2], []),
    'removeLibraryItemTag' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
    'removeUser' : IDL.Func([IDL.Principal], [Result], []),
    'renameFolder' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
    'renameLibraryItem' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
    'reopenMatter' : IDL.Func([IDL.Nat], [Result], []),
    'resumeMatter' : IDL.Func([IDL.Nat], [Result], []),
    'revokeOperations' : IDL.Func([], [Result], []),
    'searchClients' : IDL.Func(
        [ClientFilter, IDL.Nat, IDL.Nat],
        [IDL.Vec(Client)],
        ['query'],
      ),
    'searchDocuments' : IDL.Func(
        [DocumentFilter, IDL.Nat, IDL.Nat],
        [IDL.Vec(DocumentSearchResult)],
        ['query'],
      ),
    'searchLibrary' : IDL.Func(
        [LibraryFilter, IDL.Nat, IDL.Nat],
        [IDL.Vec(LibraryItemSearchResult)],
        ['query'],
      ),
    'searchMatters' : IDL.Func(
        [MatterFilter, IDL.Nat, IDL.Nat],
        [IDL.Vec(Matter)],
        ['query'],
      ),
    'setLibraryItemTags' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Text)], [Result], []),
    'setStorageBudget' : IDL.Func([IDL.Nat], [Result], []),
    'setUserRole' : IDL.Func([IDL.Principal, Role], [Result], []),
    'startLibraryUpload' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Nat),
        ],
        [Result_1],
        [],
      ),
    'startUpload' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat)],
        [Result_1],
        [],
      ),
    'suspendUser' : IDL.Func([IDL.Principal], [Result], []),
    'transferMasterController' : IDL.Func([IDL.Principal], [Result], []),
    'unarchiveLibraryItem' : IDL.Func([IDL.Nat], [Result], []),
    'unsuspendUser' : IDL.Func([IDL.Principal], [Result], []),
    'updateClient' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(ClientType),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Result],
        [],
      ),
    'updateLibraryItemDescription' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [Result],
        [],
      ),
    'updateMatter' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Opt(IDL.Principal)),
          IDL.Opt(IDL.Text),
        ],
        [Result],
        [],
      ),
    'whoAmI' : IDL.Func([], [IDL.Principal], ['query']),
  });
  
  return ThePractice;
};

export const init = ({ IDL }) => { return [IDL.Principal]; };